name: audio_app
description: Application mobile audio sécurisée - ING3 SEC

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0

  # Biométrie
  local_auth: ^2.3.0

  # Audio
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.12
  audio_session: ^0.1.21

  # HTTP pour l'API externe
  http: ^1.2.1

  # Graphiques
  fl_chart: ^0.68.0

  # Stockage local
  shared_preferences: ^2.3.1

  # Divers UI
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
